### ISSUE TITLE
support passing environment variables in addition to flags

### ISSUE THREAD

**Issue by theofficialgman** [refi64/cobalt#6]
I have a usecase as a user where I need to set variables in the environment that chromium will read. I am not able to do this with flags and currently there is no way to do this in the chromium based flatpaks. eg: https://chromium.googlesource.com/chromium/src/+/main/docs/api_keys.md#providing-keys-at-runtime

**Comment by refi64** [comment]
You can just use `flatpak override [--user if this is a user instance] org.chromium.Chromium --env=NAME=VALUE` (that's what I do for those same variables).

**Comment by theofficialgman** [comment]
I think it would be nice for this application to support environment variables itself (eg: so I can package a chromium based application using cobalt and set environment variables). it is common for chromium launch script to support both environment variables and flags and I see this project as the equivalent to such launch scripts for flatpak.
